project_id = "uhqlwmucjhnpyvgxtupw"

[functions.process-video]
verify_jwt = true

[functions.generate-script]
verify_jwt = true

[functions.ai-highlight-detection]
verify_jwt = true

[functions.youtube-search]
verify_jwt = true

[functions.process-youtube-url]
verify_jwt = true

[functions.generate-clips]
verify_jwt = true
