version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "developer"
    reviewers:
      - "developer"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      testing:
        patterns:
          - "@testing-library/*"
          - "@vitest/*"
          - "vitest"
          - "@playwright/*"
          - "msw"
      typescript:
        patterns:
          - "@types/*"
          - "typescript"
          - "typescript-eslint"
      build-tools:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "eslint"
          - "@eslint/*"
      ui-components:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "tailwindcss*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
      include: "scope"
