global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application health checks
  - job_name: 'viralclips-app'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Supabase Edge Functions health
  - job_name: 'supabase-functions'
    static_configs:
      - targets: ['your-project.supabase.co']
    metrics_path: '/functions/v1/health-check'
    scrape_interval: 60s
    scrape_timeout: 15s
    scheme: https

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom application metrics
  - job_name: 'viralclips-metrics'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Database metrics (if postgres_exporter is available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
