// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhqlwmucjhnpyvgxtupw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocWx3bXVjamhucHl2Z3h0dXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjcwMTMsImV4cCI6MjA3MTk0MzAxM30.D8dhFFBMs4xFyZM4x1b_gRoYB8HGmd7XPQlns4YOxkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});